// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lotvolt2
NumericMatrix lotvolt2(NumericVector rm, NumericVector k, NumericMatrix b, NumericVector n0, NumericVector sigma_d, NumericVector sigma_e, NumericMatrix u_d, NumericMatrix u_e);
RcppExport SEXP ecofoliosim_lotvolt2(SEXP rmSEXP, SEXP kSEXP, SEXP bSEXP, SEXP n0SEXP, SEXP sigma_dSEXP, SEXP sigma_eSEXP, SEXP u_dSEXP, SEXP u_eSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type rm(rmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type n0(n0SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type sigma_d(sigma_dSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type sigma_e(sigma_eSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type u_d(u_dSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type u_e(u_eSEXP );
        NumericMatrix __result = lotvolt2(rm, k, b, n0, sigma_d, sigma_e, u_d, u_e);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
